runtime: custom
env: flex

service: your-service-name

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  ASPNETCORE_ENVIRONMENT: development
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

handlers:
  - url: /.*
    script: auto
